<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories'] = 'Категории';
$lang['error_must_select'] = 'Трябва да изберете категория';
$lang['error_not_found'] = 'Исканата категория не може да бъде намерена.';
$lang['organize_category'] = 'Организиране на  "%s" категория';
$lang['organize'] = 'Организиране';
$lang['category_id'] = 'ID';
$lang['category_form'] = 'Категория от';
$lang['name'] = 'Име';
$lang['slug'] = 'Slug';
$lang['hidden'] = 'Скрита';
$lang['description'] = 'Описание';
$lang['excerpt'] = 'Отказ';
$lang['image'] = 'Картинка';
$lang['sequence'] = 'последователност';
$lang['seo_title'] = 'SEO име';
$lang['meta'] = 'Meta Data';
$lang['message_category_saved'] = 'Категорията е записана!';
$lang['error_file_upload'] = '<p>Няма избран файл за upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category'] = 'Категорията е изтрита.';
$lang['current_file'] = 'Текущ фаил';
$lang['confirm_delete_category'] = 'Наистина ли искате да изтриете тази категория?';
$lang['add_new_category'] = 'Нова категория';
$lang['top_level_category'] = 'Основна категория';
$lang['no_categories'] = 'Няма категории';
$lang['attributes'] = 'Атрибути';
$lang['seo'] = 'SEO';
$lang['parent'] = 'Основен';
$lang['meta_data_description'] = 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop'] = 'Влачите и пускате на продуктите в реда, който бихте искали да се появят.';
$lang['sku'] = 'SKU';
$lang['price'] = 'Цена';
$lang['sale'] = 'продажба';
$lang['max_file_size'] = 'Max File Size';
$lang['sort_name_asc'] = 'По име (A - Я)';
$lang['sort_name_desc'] = 'По име (Я - A)';
$lang['sort_price_asc'] = 'Цена ниска - висока';
$lang['sort_price_desc'] = 'Цена висока - ниска';
$lang['sort'] = 'Сортиране';
